package org.jax.gweaver.variant.orthology.domain;

import java.util.Objects;

import org.neo4j.ogm.annotation.GeneratedValue;
import org.neo4j.ogm.annotation.Id;
import org.neo4j.ogm.annotation.Index;
import org.neo4j.ogm.annotation.NodeEntity;
import org.neo4j.ogm.annotation.Relationship;

@NodeEntity(label="Variant")
public class Variant extends GeneticEntity {

	@Index(unique=true)
	private String rs_id;
	
	@Index(unique=true)
	private String id;
    
	private String ref_allele;
	private String alt_allele;
	private Float alt_allele_freq = 0F;
    private String variant_effect;
    private String biotype;


	@Relationship(type = "HAS_A", direction = Relationship.INCOMING)
	private Transcript transcript;

	// Autogenerated

	/**
	 * @return the rs_id
	 */
	public String getRs_id() {
		return rs_id;
	}


	/**
	 * @param rs_id the rs_id to set
	 */
	public void setRs_id(String rs_id) {
		this.rs_id = rs_id;
	}


	/**
	 * @return the ref_allele
	 */
	public String getRef_allele() {
		return ref_allele;
	}


	/**
	 * @param ref_allele the ref_allele to set
	 */
	public void setRef_allele(String ref_allele) {
		this.ref_allele = ref_allele;
	}


	/**
	 * @return the alt_allele
	 */
	public String getAlt_allele() {
		return alt_allele;
	}


	/**
	 * @param alt_allele the alt_allele to set
	 */
	public void setAlt_allele(String alt_allele) {
		this.alt_allele = alt_allele;
	}


	/**
	 * @return the alt_allele_freq
	 */
	public Float getAlt_allele_freq() {
		return alt_allele_freq;
	}


	/**
	 * @param alt_allele_freq the alt_allele_freq to set
	 */
	public void setAlt_allele_freq(Float alt_allele_freq) {
		this.alt_allele_freq = alt_allele_freq;
	}

	/**
	 * @return the variant_effect
	 */
	public String getVariant_effect() {
		return variant_effect;
	}


	/**
	 * @param variant_effect the variant_effect to set
	 */
	public void setVariant_effect(String variant_effect) {
		this.variant_effect = variant_effect;
	}


	/**
	 * @return the biotype
	 */
	public String getBiotype() {
		return biotype;
	}


	/**
	 * @param biotype the biotype to set
	 */
	public void setBiotype(String biotype) {
		this.biotype = biotype;
	}


	/**
	 * @return the transcript
	 */
	public Transcript getTranscript() {
		return transcript;
	}


	/**
	 * @param transcript the transcript to set
	 */
	public void setTranscript(Transcript transcript) {
		this.transcript = transcript;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result
				+ Objects.hash(alt_allele, alt_allele_freq, biotype, id, ref_allele, rs_id, transcript, variant_effect);
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (!(obj instanceof Variant))
			return false;
		Variant other = (Variant) obj;
		return Objects.equals(alt_allele, other.alt_allele) && Objects.equals(alt_allele_freq, other.alt_allele_freq)
				&& Objects.equals(biotype, other.biotype) && Objects.equals(id, other.id)
				&& Objects.equals(ref_allele, other.ref_allele) && Objects.equals(rs_id, other.rs_id)
				&& Objects.equals(transcript, other.transcript) && Objects.equals(variant_effect, other.variant_effect);
	}


	/**
	 * @return the id
	 */
	public String getId() {
		return id;
	}


	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}


	// Auto-generated stuff: 
}